spring:
  output:
    ansi:
      enabled: always
  application:
    name: fintech
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: NEVER

jwt:
  secret: ${JWT_SECRET}
  expiration-hours: 72 # 3 days