spring:
  output:
    ansi:
      enabled: always
  application:
    name: fintech
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            timeout: 2000

server:
  error:
    include-stacktrace: NEVER

jwt:
  secret: ${JWT_SECRET}
  expiration-hours: 72 # 3 days

auth0:
  clientId: ${AUTH0_CLIENT_ID}
  publicKeysUri: ${AUTH0_PUBLIC_KEYS_URI}

frontend:
  url: ${FRONTEND_URL}

backend:
  url: ${BACKEND_URL}

rss_feed:
  urls: >
    https://api.rss2json.com/v1/api.json?rss_url=https://eleconomista.com.ar/economia/feed/,
    https://api.rss2json.com/v1/api.json?rss_url=https://eleconomista.com.ar/finanzas/feed/

ml:
  recommended-assets:
    url: https://fast-api-fintech-production.up.railway.app/recommend-assets/